name: voici-dev
channels:
  - conda-forge
dependencies:
  - pip
  - black
  - yarn=1
  - nodejs=18
  - pip:
    - ruff==0.0.258
    - voila>=0.5.0a3,<0.6.0
    - voila-material>=0.4.3
    - jupyterlite-core[lab]>=0.1.0,<0.2.0
    - jupyterlite-xeus-python >= 0.7.0
