name: voici-dev
channels:
  - conda-forge
dependencies:
  - pip
  - ruff
  - pytest
  - yarn=3
  - nodejs=22
  - pip:
    - ruff==0.4.5
    - voila>=0.5.5
    - voila-material>=0.4.3
    - jupyterlite-core[lab]>=0.6.0,<0.7.0
