name: voici
channels:
  - conda-forge
  - conda
dependencies:
  - myst-parser
  - nodejs=18
  - sphinx
  - pydata-sphinx-theme
  - jupyterlab-night
  - yarn=1
  - pip:
    - jupyterlite-xeus-python >= 0.9.0,<0.10.0
    - sphinxcontrib-video
    - ..
